export const ADMIN_PERMISSIONS = [
  'MANAGE_VENDORS',
  'MANAGE_USERS',
  'MANAGE_VERIFICATIONS',
  'MANAGE_REVIEWS',
  'MANAGE_LOCATIONS',
  'MANAGE_AMENITIES',
  'MANAGE_ARCHIVE',
  'MANAGE_BLOGS'
];
